### ISSUE TITLE
Entrypoint configuration

### ISSUE THREAD

**Issue by mertenvg** [whitecypher/gapp#1]
For cases where main/entry-point go files are not contained in the root of a repository there should be an option to indicate which package(s) to look in for root dependencies.

`vgo add-main relative/sub-package/path [relative/sub-package/path2 ...]`

These should be stored in the vgo.yaml manifest

``` yaml
package: github.com/my/project
main:
 - relative/sub-package/path
 - relative/sub-package/path2
```

secondarily, the opposite should also be possible.

`vgo rm-main relative/sub-package/path [relative/sub-package/path2 ...]`
